################################################################################
# ENVIRONMENT TEMPLATES
################################################################################

# can't merge arrays in YAML so we have to duplicate stuff between 36 and 37
# and include all variables that are relevant across all operating systems
env_py36: &env_py36
  env:
    - PYTHON_VERSION=3.6.8
    - PY_MM=36
    - TOXENV=py${PY_MM}
    - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH
env_py37: &env_py37
  env:
    - PYTHON_VERSION=3.7.4
    - PY_MM=37
    - TOXENV=py${PY_MM}
    - PATH=/c/Python${PY_MM}:/c/Python${PY_MM}/Scripts:$PATH


################################################################################
# OS JOB TEMPLATES
################################################################################

osx_base_job: &osx_base_job
  os: osx
  osx_image: xcode8.3
  language: sh
  before_install:
    - brew upgrade pyenv
    - pyenv install -s $PYTHON_VERSION
    - export PYENV_VERSION=$PYTHON_VERSION
    - export PATH="/Users/travis/.pyenv/shims:${PATH}"
    - pip3 install -U pip
  install:
    - pip3 wheel --no-deps -w dist/ .
    - pip3 install tox

win_base_job: &win_base_job
  os: windows
  language: sh
  before_install:
    # vcredist2010 is required for loading the apriltags.dll when building with msvc.
    # I don't know why exactly, but loading the DLL will fail otherwise on travis.
    - choco install vcredist2010
    - choco install python --version $PYTHON_VERSION
    - python -m pip install -U pip
  install:
    - python -m pip wheel --no-deps -w dist/ .
    - python -m pip install tox

ubuntu_base_job: &ubuntu_base_job
  os: linux
  services: docker
  before_install:
    - docker pull quay.io/pypa/manylinux2010_x86_64
  install:
    - chmod +x ./.travis/manylinux_build_wheel.sh
    - >
      docker run --rm
      -v `pwd`:/io
      quay.io/pypa/manylinux2010_x86_64
      /io/.travis/manylinux_build_wheel.sh
      $PY_MM

ubuntu_trusty_base_job: &ubuntu_trusty_base_job
  <<: *ubuntu_base_job
  dist: trusty
  before_script:
    # update pyenv
    - pushd /opt/pyenv/plugins/python-build/../..
    - git fetch && git fetch --tags
    - git checkout v1.2.13
    - popd
    # install python
    # NOTE: does not work for 3.7.4 out of the box currently!
    - pyenv install -s $PYTHON_VERSION
    - pyenv global $PYTHON_VERSION
    - pip3 install -U pip
    - pip3 install tox

ubuntu_bionic_base_job: &ubuntu_bionic_base_job
  <<: *ubuntu_base_job
  dist: bionic
  # bionic has newest python available via travis
  language: python
  before_script:
    - pip3 install -U pip
    - pip3 install tox
  

################################################################################
# DEFINE JOB MATRIX
################################################################################

matrix:
  include:
    - name: "Python 3.6.8 on OSX 10.12 (xcode8.3)"
      <<: *osx_base_job
      <<: *env_py36

    - name: "Python 3.7.4 on OSX 10.12 (xcode8.3)"
      <<: *osx_base_job
      <<: *env_py37

    - name: "Python 3.6.8 on Windows"
      <<: *win_base_job
      <<: *env_py36
    
    - name: "Python 3.7.4 on Windows"
      <<: *win_base_job
      <<: *env_py37

    - name: "Python 3.6.8 on Ubuntu 14.04 (using manylinux wheel)"
      <<: *ubuntu_trusty_base_job
      <<: *env_py36

    - name: "Python 3.6.8 on Ubuntu 18.04 (using manylinux wheel)"
      <<: *ubuntu_bionic_base_job
      python: 3.6.8
      <<: *env_py36
    
    - name: "Python 3.7.4 on Ubuntu 18.04 (using manylinux wheel)"
      <<: *ubuntu_bionic_base_job
      python: 3.7.4
      <<: *env_py37


################################################################################
# RUN AND DEPLOY (OS INDEPENDENT)
################################################################################

script:
  - tox --installpkg ./dist/pupil_apriltags*.whl

deploy_template: &deploy_template
  on:
    tags: true
    branch: master
  skip_cleanup: true

deploy:
  - provider: releases
    <<: *deploy_template
    api_key: $GitHubOAUTH
    file_glob: true
    file: "./dist/pupil_apriltags*.whl"
  - provider: script
    <<: *deploy_template
    script: bash ./.travis/pypi_deploy.sh
